E Commere/Controllers/CategoriesController.cs
using E_Commere.Data;
using E_Commere.Data.Services;
using E_Commere.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace E_Commere.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly ICategoryServices services;
        public CategoriesController(ICategoryServices _services)
        {
            services = _services;
        }
        public async Task<IActionResult> Index()
        {
            var categories = await services.GetAllAsync();
            return View(categories);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create([Bind("Name,Description")] Category category)
        {
            if (ModelState.IsValid)
            {
                await services.CreateAsync(category);
                return RedirectToAction(nameof(Index));
            }
            return View(category);

        }
        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            var category =await services.GetByIdAsync(id);
            if(category != null)
            {
                return View(category);
            }
            return View("NotFound");
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var category = await services.GetByIdAsync(id);
            if (category != null)
            {
                return View(category);
            }
            return View("NotFound");
        }
        [HttpPost]
        public async Task<IActionResult> Edit(Category category)
        {

            if (!ModelState.IsValid) 
            {
                return View("Not Found");
            }
            await services.UpdateAsync(category);
            return RedirectToAction(nameof(Index));
        }
        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            await services.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

    }
}

E Commere/Controllers/OrdersController.cs
using E_Commere.Data.Cart;
using E_Commere.Data.Services;
using Microsoft.AspNetCore.Mvc;

namespace E_Commere.Controllers
{
    public class OrdersController : Controller
    {
        readonly private IProductService _productService;
        readonly private ShoppingCart _shoppingCart;
        readonly private IOrderServices _orderServices;
        public OrdersController(IProductService productService, ShoppingCart shoppingCart, IOrderServices orderServices)
        {
            _productService = productService;
            _shoppingCart = shoppingCart;
            _orderServices = orderServices;
        }
        public async Task<IActionResult>Index()
        {
            string userId = "";
            var order =await _orderServices.GetOrderByUserIdAsync(userId);
            return View(order);
        }

        public IActionResult ShoppingCart()
        {
            var item = _shoppingCart.GetshoppingCartItems();
            ViewBag.Total =_shoppingCart.GetShoppingCartTotal();
            return View(item);
        }
        public async Task<IActionResult> AddToCart(int id)
        {
            var result = await _productService.GetByIdAsync(id);
            if (result != null)
            {
                await _shoppingCart.AddItemToShoppingCart(result);
            }
            return RedirectToAction("ShoppingCart");
        }
        public async Task<IActionResult> RemoveFromCart(int id)
        {
            var result = await _productService.GetByIdAsync(id);
            if (result != null)
            {
                await _shoppingCart.RemoveItemFromShoppingCart(result);
            }
            return RedirectToAction("ShoppingCart");
        }
        public async Task<IActionResult> CompleteOrder()
        {
            var item = _shoppingCart.GetshoppingCartItems();
            string userId = "";
            await _orderServices.StoreOrdersAsync(item, userId);
            _shoppingCart.ClearShoppingCart();
            return View("CompleteOrder");
        }
    }
}

E Commere/Controllers/ProductsController.cs
using E_Commere.Data;
using E_Commere.Data.Base;
using E_Commere.Data.Services;
using E_Commere.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace E_Commere.Controllers
{
    public class ProductsController : Controller
    {
        private readonly  IProductService service;
        private readonly ICategoryServices CatServices;
        public ProductsController(IProductService _service, ICategoryServices _CarServices)
        {
              service = _service;
            CatServices = _CarServices; 
        }
        public async Task<IActionResult> Index(string SearchTerm)
        {
            var product = await service.GetAllAsync(x=> x.Category);
            if(!string.IsNullOrEmpty(SearchTerm))
            {
                product = product.Where(x=> x.Name.Contains(SearchTerm)).ToList();
            }
            return View(product);
        }
        public async Task<IActionResult>Details(int id)
        {
            var product = await service.GetByIdAsync(id,x=> x.Category);
            return View(product);
        }
        [HttpGet]
        public async Task<IActionResult>Create()
        {
            ViewBag.CategoryId = await CatServices.GetAllAsync();
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Product product)
        {
            if (ModelState.IsValid)
            {
                await service.CreateAsync(product);
                await service.SaveChanges();
                return RedirectToAction("Index");
            }
            return View("NotFound");
        }
        [HttpGet]
        public async Task<IActionResult>Edit(int id)
        {
            ViewBag.CategoryId = await CatServices.GetAllAsync();
            var productId = await service.GetByIdAsync(id, x=> x.Category);
            return View(productId);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(Product product)
        {
            if (ModelState.IsValid)
            {
                await service.UpdateAsync(product);
                await service.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(product);

        }
        public async Task<IActionResult>Delete(int id)
        {
            await service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

E Commere/Views/Shared/NotFound.cshtml
@{
	ViewData["Title"] = "Not Found";
}

<div class="row">
	<div class="col-md-8 offset-2">
		<img src="~/Imeges/404 (1).jpg" style="width:80%; height:500px"/>
	</div>
	<div class="col=md-4 offset-5">
		<a class="btn btn-outline-success" asp-action="Index" asp-controller="Products">
			<i class="fas fa-reqular fa-arrow-rotate-right"></i>
			Go To Home Page
		</a>
	</div>
</div>

E Commere/Views/Shared/_CreateItem.cshtml
@model string

<div class="text-white" style="position:fixed;right:50px;bottom:70px;">
	<a asp-action="Create" asp-controller="@Model" class="btn btn-outline-success">
		<i class="fas fa-reqular fa-plus-square mr-2"></i>
		Create
	</a>
</div>

E Commere/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - E_Commere</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/E_Commere.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3" style="padding-left:70px">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Products" asp-action="Index">E_Commere</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1" >
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="Index">Categories</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Products</a>
                        </li>
                    </ul>
                    <form class="d-flex align-items-center " style="padding-right:90px" asp-action="Index" asp-controller="Products">
                        <input name="SearchTerm" type="text" class="form-control" placeholder="Search here..." autocomplete="off" />
                        <button type="submit" class="btn btn-success">
                            <i class="fas fa-regular fa-search"></i>
                        </button>
                        <ul class="navbar nav">
                            @await Component.InvokeAsync("ShoppingCartSummery")
                        </ul>>
                        <div class="dropdown">
                            <button class="btn btn-outline-success dropdown-toggle"
                                    id="profile-btn"
                                    data-bs-toggle="dropdown"
                                    aria-expanded="false">
                                <i class="fas fa-user me-1"></i>
                                Hello,...
                            </button>

                            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="profile-btn">
                                <li>
                                    <a class="dropdown-item" asp-action="Index" asp-controller="Orders">
                                        <i class="fas fa-list-check me-2"></i>
                                        Orders
                                    </a>
                                </li>
                            </ul>
                        </div>

                    </form>
                    
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2026 - E_Commere - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false) 
</body>
</html>